"""Add game_user Association Table

Revision ID: a7001175a4c3
Revises: 76fc92a6bb86
Create Date: 2023-06-12 17:11:38.210811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7001175a4c3'
down_revision = '76fc92a6bb86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
